### ISSUE TITLE
[FEAT] pull down 버튼 연락 목표 + 연결

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#111]
## 💡 Issue
연락 목표 페이지가 추가됨에 따라 해당 세팅 페이지를 연결할 pull down 버튼을 만들고, 연결 및 case 처리

## 📝  todo
- [ ] pull down 버튼에 목표 페이지 버튼 추가
- [ ] 온보딩 3 페이지 setting, onboarding case 나누기
- [ ] 온보딩 3 페이지와 pull down 버튼 연결
