### ISSUE TITLE
[FEAT] 추가하기, 설정하기 타이틀 UI 변경

### ISSUE THREAD

**Issue by glitterer** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#114]
## 💡 Issue
추가하기와 설정하기 뷰에서 large title로 배치되어있는 것을 navigation bar title 로 변경합니다.

## 📝  todo
- [x] 추가하기 large title 변경
- [x] 추가하기 navigation title 구현
- [x] 설정하기 largetitle 변경
- [x] 설정하기 navigation title 구현
