### ISSUE TITLE
[FEAT] 보고 도움이 되도록 만들어보기..?!

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#14]
## 💡 Issue

코드 구현하다가 막히는 부분이 있으면 보고 도움이 될 수 있도록 이쪽에 작업을 해보도록 하겠습니당

## 📝  todo

- [x] 온보딩1 UI 구현
- [x] 공동 버튼 컴포넌트 만들기
- [x] 권한설정 허용
- [x] 온보딩2 UI구현
- [x] 온보딩2 Main 이동 기능 구현
- [x] 가족 퀘스천 UI 구현
- [ ] 가족 퀘스턴 모델 구현 + 데이터 만들기(JSON)
- [x] 우리 가족 리스트 TableView 구현
- [x] 우리 가족 셀 UI 구현
- [ ] 우리 가족 셀에 데이터 뿌리기
- [ ] 모든 뷰 연결하기
- [x] 우리 가족 셀의 버튼 구현
- [ ] 푸쉬 알림 구현
- [ ] 추가하기 뷰 UI 구현
- [ ] 프로필 이미지 모달 UI 구현 (CollectionView)
- [ ] 추가하기 뷰 기능 구현
- [ ] 수정하기 뷰 삭제 기능 구현
- [x] 세팅 TableView 구현

**Comment by Gobans** [comment]
띠용 ㄷㄷ

**Comment by dangsal** [comment]
다들 잘 하는거 같아서 이거 필요없을거같아서 중지..!! 후후 모르는거 있으면 언제든 물어봐유~.~

**Comment by glitterer** [comment]
> 다들 잘 하는거 같아서 이거 필요없을거같아서 중지..!! 후후 모르는거 있으면 언제든 물어봐유~.~

너무 큰 도움이 되었습니다!! 🙇‍♂️
