### ISSUE TITLE
[FEAT] 온보딩 2와 3 모호하지 않게 변경

### ISSUE THREAD

**Issue by glitterer** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#145]
## 💡 Issue
UT 이후, 온보딩 2/3의 모호함이 있다고 하여 이를 수정합니다.

## 📝  todo
- [x] 온보딩 2 title 수정
- [x] 온보딩 3 title 수정
- [x] 온보딩 3 stepper 없애기
- [x] 온보딩 3 스크린샷 추가

## 📸 Screenshot
 <img width="236" alt="스크린샷 2022-08-04 오후 1 07 17" src="https://user-images.githubusercontent.com/50728605/182760933-a1972c6b-518a-4d0f-991d-97bfa0ae2ac7.png"> <img width="235" alt="스크린샷 2022-08-04 오후 1 07 23" src="https://user-images.githubusercontent.com/50728605/182760923-6180b600-d76e-4fe7-900a-024bc0e94de2.png">
