### ISSUE TITLE
[FEAT] 모달 collectionView 

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#21]
## 💡 Issue
가족 구성원들 캐릭터를 고르는 모달 화면의 collection view를 만듭니다

## 📝  todo
- [ ] 취소, 변경 버튼 ( 상단에 있는 경우 bar button item으로)
- [ ] 취소, 변경 버튼 ( 하단에 있는 경우 custom button)
- [ ] collection view layout

## 📸 Screenshot

왼쪽 : 기존, 오른쪽 : 개선 
기존의 모달과 collection view의 구조가 살짝 어정쩡한 것 같아 오른쪽과 같이 개선을 해봤습니다
추후에 이야기 해보면 좋을 것 같습니다
sprint2!!
@Gobans @glitterer @seongmin221 @dangsal 
<p aling="left">
<img width="250" alt="스크린샷 2022-07-17 오후 9 42 28" src="https://user-images.githubusercontent.com/26588989/179399018-6be9385d-2596-4eb9-8999-4728902e0ed9.png">
<img width="250" alt="스크린샷 2022-07-17 오후 9 47 20" src="https://user-images.githubusercontent.com/26588989/179399022-dd7f037b-87f7-47d5-a33f-a8766db4b8df.png"
</p>
