### ISSUE TITLE
[FEAT] AddingView 페이지 기능 구현

### ISSUE THREAD

**Issue by dangsal** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#40]
## 💡 Issue

[FEAT] AddingView 페이지 기능 구현

## 📝  todo
- [x] 이름 제한 
- [x] 키보드 위치에 따른 배치
- [x] 아무데나 눌러도 눌러도 키보드 내리기
- [x] 이미지에 탭 제스처 등록
- [ ] 가족 정보 UserDefault에 저장 -> 뷰끼리 연결하고 하는걸로
