### ISSUE TITLE
[FEAT] change FamilyTableView's design

### ISSUE THREAD

**Issue by seongmin221** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#51]
## 💡 Issue

- 첫 스프린트 끝난 뒤 바뀐 mainviewcontroller의 familyTableView 디자인 변경

## 📝  todo
- [x] Cell 백그라운드 컬러 없애기
- [x] divider 없애기
- [x] tableview 양 옆 padding 없애기
- [x] 버튼 모양 변경

## 📸 Screenshot

<img src="https://user-images.githubusercontent.com/72431640/180181101-9e877f21-c3de-4559-909e-07422c28a4bb.png" width="250">
