### ISSUE TITLE
[FEAT] Pull down setting button UI & add button

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#54]
## 💡 Issue
- setting button과 add button 만들기
- setting button의 각 항목들에 맞는 기능 연결
- add button으로 add 화면 연결

## 📝  todo
- [x] setting button과 add button 만들기
- [x] add button으로 add 화면 연결
- [x] setting button (알림 설정 화면으로 이동 연결)
- [x] setting button (주기 설정 화면으로 이동 연결)

## 📸 Screenshot
<img width="300" alt="스크린샷 2022-07-22 오후 2 15 11" src="https://user-images.githubusercontent.com/26588989/180367798-14ed868f-00af-4d89-b3b4-abe85c4e5817.png">
