### ISSUE TITLE
[FEAT] userDefaults 데이터 뿌리기 & 가공하기

### ISSUE THREAD

**Issue by seongmin221** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#56]
## 💡 Issue

userDefaults에 있는 데이터를 familyTableView에 뿌려주기

## 📝  todo
- [ ] 전화 버튼 누르면 userDefaults finalContactDiffDay 0으로 갱신
- [ ] 전화 버튼 누르면 연락일 text “오늘 연락했어요”로 갱신
- [ ] 전화 버튼 누르면 등록된 알림 내용을 갱신
- [ ] familyMemberDataModel 알맞게 변경
