### ISSUE TITLE
[FEAT] 온보딩2 뷰 기능(시작버튼)과 뷰(온보딩1/메인) 연결: UserDefaults

### ISSUE THREAD

**Issue by glitterer** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#58]
## 💡 Issue
온보딩2 뷰에서 시작하기 버튼을 누르면
1. UserDefaults에 유저 알림 횟수 저장
2. UserDefaults에 온보딩 확인 여부 저장

이후에는 **앱을 처음 실행해서 온보딩 화면을 본 적이 없으면 온보딩 화면을 띄우고,
만약 이미 온보딩 화면을 본 상태 (= 온보딩 화면의 "시작하기" 버튼을 누른 후)이면 메인 화면이 뜨도록 구현.**
* 이에 대해서는 방법은 2가지가 있다:
   1. scene delegate에서 if-else 문으로 하는 것
   2. mainviewcontroller에서 처리하는 것

**우리가 사용할 방법은 2번 mainviewcontroller에서 처리하는 것**으로 결정되었다.
 
## 📝  todo
- [x] UserDefaults에 유저 알림 횟수 저장하도록 구현
- [x] UserDefaults에 온보딩 확인 여부 저장하도록 구현
- [x] MainViewController에서 처리하는 userdefaults 값을 가져온다.
- [x] model view를 사용하여 온보딩을 출력한다 (full screen)
- [x] 온보딩1과 2 연결 

## 📸 Screenshot
<img width="250" src="https://user-images.githubusercontent.com/50728605/180439247-628e0e23-3670-4aad-9b67-ef95935fe322.png">
