### ISSUE TITLE
[FEAT] Onboarding case에 따른 confirm button action 처리

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#76]
## 💡 Issue
setting, onboarding 중 어디에서 onboarding two controller로 갔는지에 따라 다른 처리가 필요합니다

## 📝  todo
- [ ] 버튼 타이틀 switch case
- [ ] start button name 변경
- [ ] start button action switch case
