### ISSUE TITLE
[FEAT] 연락 목표기능구현

### ISSUE THREAD

**Issue by Gobans** [DeveloperAcademy-POSTECH/MC3-Team14-HyojaDongHyojadeul#95]
## 💡 Issue

유저가 설정한 연락 목표에 따라 피드백을 보여줄 수 있도록 기능구현

## 📝  todo
- [ ] userContactGoal Userdefaults에 생성
- [ ] 처음 접속 시 마지막 접속일에서 부터 일요일이 지났는지 체크. 지났다면, contactGoalCount 초기화.
- [ ] 하루가 지나면 피드백 받을 수 있도록 isFeedbackPresented를 false로 변경.
- [ ] 연락을 하면 isFeedbackPresented 를 true로 변경.
- [ ] 연락을 하면 contactGoalCount에 1을 더해서 갱신
